### ISSUE TITLE
Outlook (new) bị gỡ ra khỏi Windozes

### ISSUE THREAD

**Issue by gitchuon** [SucklessWindows/SucklessWindows#4]
![image](https://github.com/SucklessWindows/SucklessWindows/assets/155883444/8d5618dd-13b9-40c9-8d82-f3223a86f8b3)
Sau khi reboot thì kh thấy Outlook (bản mới) đâu, kiểm tra lại các config thì kh thấy cái nào nhắc đến việc gỡ Outlook. Anh bổ sung thêm config gỡ Outlook vào nhé

**Comment by gitchuon** [comment]
lên store tải lại dùng bth, nhưng mà bổ sung vào thì vẫn hơn, có 1 số ng thực sự cần cái này

**Comment by p3nguin-kun** [comment]
Tôi ditch hết mấy cái bloatware của M$ và thay thế bằng phần mềm FOSS, nếu cần thì tự cài lại.
