### ISSUE TITLE
icon của Windozes Defender ở system tray bị mất

### ISSUE THREAD

**Issue by gitchuon** [SucklessWindows/SucklessWindows#5]
![image](https://github.com/SucklessWindows/SucklessWindows/assets/155883444/4cc20cf7-5979-49c0-982f-39e17640ef60)
(Configs đã chọn: không tắt windozes defender)
Kiểm tra chỗ Startup apps kh thấy phần khởi động cho cái icon, có lẽ do vậy mà kh thấy nó hiện lên.
![image](https://github.com/SucklessWindows/SucklessWindows/assets/155883444/7e9c7c55-bf5f-4d4d-bc8f-78f269d5a386)

**Comment by p3nguin-kun** [comment]
thì disable cái icon đi mà
